# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_aab do
      gradle(task: 'clean')
      gradle(
        task: 'bundle',
        build_type: 'Release',
        print_command: true
      )
      upload_to_play_store(
          track:'production',
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true
      )
  end

  desc "Distribute app to the Firebase"
  lane :distribute do
      gradle(task: 'clean')
      gradle(
          task: 'bundle',
          build_type: 'Release',
          print_command: true
      )
      firebase_app_distribution(
          app: "1:1019350039203:android:9cd8b741a970ae86e2dd16",
          testers: "tester1@company.com, tester2@company.com",
          groups: "qa-team, trusted-testers",
          release_notes: "Lots of amazing new features to test out!"
      )
  end
end